### ISSUE TITLE
fiware/orion:3.7.0 にしないと、orionが起動しない

### ISSUE THREAD

**Issue by KazukiSakai1974** [c-3lab/fiware-learning-handson#34]
ハンズオンコンテンツ提供当時から、fiware/orionのバージョンもあがっており、きっとmongoとのバージョン不一致で起動しないのではないかと推察します。研修という意味からは、説明当時のバージョン固定でもいいかと思うので、docker-compose.yml のimage部分をタイトルのようにバージョン固定に変更するのはどうでしょうか。

**Comment by ryo-ma** [comment]
ありがとうございます。
暫定対応としてはFIWARE Orion側のバージョンをmongo4.4に合わせて固定するというのが良いかと思いますが、もしこのハンズオンの利用ニーズがあるのであればFIWARE Orionの新しいバージョンに対応させるのも良いかもしれません。
