### ISSUE TITLE
part7-FIWARE Orionのログ設定

### ISSUE THREAD

**Issue by ryo-ma** [c-3lab/fiware-learning-handson#4]
# ログ設定
FIWARE Orionのログ設定について解説
FIWARE Orionにデータを投入して実際に出力されたログを確認する

参考
https://fiware-orion.readthedocs.io/en/1.15.0/admin/logs/index.html

## データの投入
データ投入時のログの確認と解説

## 通知(Subscription)
通知時のログを確認と解説

## コマンドライン引数で設定できるログ設定

**Comment by k-oizumi-abel** [comment]
その他のPartと比較して、ログ項目の説明など情報量が多いため、
現在のままの形とするか、公式文書のアップデート対応なども考慮し、
公式ドキュメントの参照URLのみとするか検討が必要かと思います。
